// Code generated by "stringer -type=lockerMode"; DO NOT EDIT.

package distributedlocker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[lockerModeCommon-0]
	_ = x[lockerModeRead-1]
	_ = x[lockerModeWrite-2]
}

const _lockerMode_name = "lockerModeCommonlockerModeReadlockerModeWrite"

var _lockerMode_index = [...]uint8{0, 16, 30, 45}

func (i lockerMode) String() string {
	if i < 0 || i >= lockerMode(len(_lockerMode_index)-1) {
		return "lockerMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lockerMode_name[_lockerMode_index[i]:_lockerMode_index[i+1]]
}
